### ISSUE TITLE
bug when "autoRename": false

### ISSUE THREAD

**Issue by LyoNick** [jjlharrison/gulp-rtlcss#2]
i.e try to set `"autoRename": false` inside a config file `.rtlcssrc`
and run with this css:

``` css
.pull-left {left: auto;}
.pull-left {content: ' ';}
```

with the command-line `rtlcss sample.css sample-rtl.css` the result are:

``` css
.pull-left {right: auto;}
.pull-left {content: ' ';}
```

wrong result with `gulp-rtlcss`

``` css
.pull-left {right: auto;}
.pull-right {content: ' ';}
```

`rtlcss version: 1.4.3`

By default RTLCSS will auto rename any selector having directional keywords but with no directional declarations,
gulp-rtlcss ignore the option to turn auto rename off completely. (perhaps it ignore the entire config file, i haven't tested it that far).
